apiVersion: v1
kind: Service
metadata:
  name: test-app-service # Remplace l'appel à include par un nom fixe pour tester
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
  - port: 80
    targetPort: 80
